-- =============================================================================
-- Database: decisions
-- Owner:    decision-service
--
-- This file documents the schema generated by Hibernate from the JPA entity
-- classes. It is reference documentation, not a migration.
--
-- VERIFIED against the live deployment on 2026-07-26 using verify-schema.sh.
-- Re-verify after any change to the entity annotations.
--
-- Column order is alphabetical after the primary key, which is how Hibernate
-- emits it. Three columns carry explicit @Column(length = ...) annotations —
-- decision_id, decision and reasoning — while the rest fall back to the
-- VARCHAR(255) default. That inconsistency is reproduced faithfully here
-- rather than tidied, because this file is meant to match the database.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- eligibility_decision
--
-- Immutable audit record of every eligibility decision produced by the rules
-- engine. APPEND-ONLY: a row is never updated. A changed assessment inserts a
-- new row with a new decision_id.
--
-- user_id is deliberately NOT unique. A worker accumulates one row per
-- assessment, and the sequence of rows is the record of how the platform's
-- view of that worker evolved as evidence accumulated. The current decision
-- is the row with the greatest decided_at for that user_id.
--
-- The three input-signal columns (average_monthly_income,
-- income_confidence_score, income_stability_label) are denormalised copies of
-- values that also live in income_verification_result. This is intentional.
-- That table holds one mutable row per worker, overwritten on every new pay
-- event; if this audit record referenced it rather than copying it, then
-- reconstructing a past decision would read today's income figure and produce
-- a different answer.
--
-- Basel II model risk management requires model outputs to be independently
-- reproducible, and Regulation B requires that the reason given to a declined
-- consumer be the reason that actually applied. Neither is satisfiable unless
-- the inputs are frozen at decision time. The redundancy is the control.
-- -----------------------------------------------------------------------------
CREATE TABLE eligibility_decision (
    -- UUID generated per decision. Not derived from user_id.
    decision_id              VARCHAR(64)                   PRIMARY KEY,

    -- Input signals, snapshotted at decision time. See note above.
    average_monthly_income   DOUBLE PRECISION              NOT NULL,

    -- 30% of average_monthly_income for approvals, 10% for referrals,
    -- 0 for denials.
    credit_limit_usd         DOUBLE PRECISION              NOT NULL,

    -- Evaluation time. Combined with the append-only design, this is what
    -- makes the table a time series. Stored with time zone so the instant is
    -- unambiguous — a decision timestamp that could not be placed on an
    -- absolute timeline would undermine the audit trail it exists to provide.
    decided_at               TIMESTAMP(6) WITH TIME ZONE   NOT NULL,

    -- APPROVED | REVIEW | DENIED
    -- REVIEW is a referral to a human underwriter, not a soft denial.
    decision                 VARCHAR(32)                   NOT NULL,

    income_confidence_score  DOUBLE PRECISION              NOT NULL,

    -- Declared length is the Hibernate default, not a domain constraint;
    -- the longest value the application produces is INSUFFICIENT_DATA.
    income_stability_label   VARCHAR(255)                  NOT NULL,

    -- Plain-language statement of which rules fired and why. Written for the
    -- affected consumer rather than for an engineer: this is the raw material
    -- for an adverse action notice under Regulation B. The 2000-character
    -- length is explicit in the entity, not a default.
    reasoning                VARCHAR(2000)                 NOT NULL,

    -- 18.99 stable approval, 22.99 moderate approval, 24.99 referral,
    -- 0 denial. Advisory: the consuming lender sets the actual rate.
    suggested_apr            DOUBLE PRECISION              NOT NULL,

    -- Worker identifier. NOT unique — see the note above.
    user_id                  VARCHAR(255)                  NOT NULL
);


-- -----------------------------------------------------------------------------
-- Indexes present in the live database
--
--   eligibility_decision_pkey  PRIMARY KEY, btree (decision_id)
--
-- Nothing else. Every read in this service filters on user_id and orders by
-- decided_at, neither of which is the primary key, so both the current-decision
-- lookup and the history retrieval are sequential scans followed by a sort.
-- See recommended-indexes.sql.
-- -----------------------------------------------------------------------------
