-- =============================================================================
-- Database: decisions
-- Owner:    decision-service
--
-- This file documents the schema currently generated by Hibernate from the
-- JPA entity classes. It is reference documentation, not a migration.
--
-- Verify against the live database before relying on it:
--     ./verify-schema.sh
-- =============================================================================


-- -----------------------------------------------------------------------------
-- eligibility_decision
--
-- Immutable audit record of every eligibility decision produced by the rules
-- engine. APPEND-ONLY: a row is never updated. A changed assessment inserts a
-- new row with a new decision_id.
--
-- user_id is deliberately NOT unique. A worker accumulates one row per
-- assessment, and the sequence of rows is the record of how the platform's
-- view of that worker evolved as evidence accumulated. The current decision
-- is the row with the greatest decided_at for that user_id.
--
-- The three input-signal columns (average_monthly_income,
-- income_confidence_score, income_stability_label) are denormalised copies of
-- values that also live in income_verification_result. This is intentional.
-- That table holds one mutable row per worker, overwritten on every new pay
-- event; if this audit record referenced it rather than copying it, then
-- reconstructing a past decision would read today's income figure and produce
-- a different answer.
--
-- Basel II model risk management requires model outputs to be independently
-- reproducible, and Regulation B requires that the reason given to a declined
-- consumer be the reason that actually applied. Neither is satisfiable unless
-- the inputs are frozen at decision time. The redundancy is the control.
-- -----------------------------------------------------------------------------
CREATE TABLE eligibility_decision (
    -- UUID generated per decision. Not derived from user_id.
    decision_id              VARCHAR(64)       PRIMARY KEY,

    -- Worker identifier. NOT unique — see the note above.
    user_id                  VARCHAR(128)      NOT NULL,

    -- APPROVED | REVIEW | DENIED
    -- REVIEW is a referral to a human underwriter, not a soft denial.
    decision                 VARCHAR(32)       NOT NULL,

    -- 30% of average_monthly_income for approvals, 10% for referrals,
    -- 0 for denials.
    credit_limit_usd         DOUBLE PRECISION  NOT NULL,

    -- 18.99 stable approval, 22.99 moderate approval, 24.99 referral,
    -- 0 denial. Advisory: the consuming lender sets the actual rate.
    suggested_apr            DOUBLE PRECISION  NOT NULL,

    -- Input signals, snapshotted at decision time. See note above.
    average_monthly_income   DOUBLE PRECISION  NOT NULL,
    income_confidence_score  DOUBLE PRECISION  NOT NULL,
    income_stability_label   VARCHAR(32)       NOT NULL,

    -- Plain-language statement of which rules fired and why. Written for the
    -- affected consumer rather than for an engineer: this is the raw material
    -- for an adverse action notice under Regulation B.
    reasoning                VARCHAR(2000)     NOT NULL,

    -- Evaluation time. Combined with the append-only design, this is what
    -- makes the table a time series.
    decided_at               TIMESTAMP         NOT NULL
);
