-- =============================================================================
-- Database: incomeverification
-- Owner:    income-verification-service
--
-- This file documents the schema generated by Hibernate from the JPA entity
-- classes. It is reference documentation, not a migration: the running
-- database is created by Hibernate, not by executing this file.
--
-- VERIFIED against the live deployment on 2026-07-26 using verify-schema.sh.
-- Re-verify after any change to the entity annotations.
--
-- Two properties below are artefacts of generation rather than design
-- decisions, and are reproduced faithfully so that this file matches reality:
--
--   1. Column order is alphabetical after the primary key. Hibernate emits
--      columns in that order; it carries no meaning.
--
--   2. String columns without an explicit @Column(length = ...) annotation
--      default to VARCHAR(255), including columns whose domain is a short
--      enumeration. In PostgreSQL a varchar is stored as a variable-length
--      value, so an oversized declared length costs nothing in storage — but
--      it does mean the column accepts values the application will never
--      produce. See recommended-indexes.sql for the CHECK constraints that
--      would close that gap.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- payroll_event_record
--
-- Historical record of every payroll event received for a worker. Retained so
-- that the confidence score can be computed over a rolling window rather than
-- from a single observation. Rows are inserted, never updated.
-- -----------------------------------------------------------------------------
CREATE TABLE payroll_event_record (
    id                BIGSERIAL                     PRIMARY KEY,

    employer_name     VARCHAR(255),

    -- Earnings before deductions. Retained for completeness; not used in scoring.
    gross_pay         DOUBLE PRECISION              NOT NULL,

    -- Earnings after deductions. This is the value the confidence score is
    -- computed from, since disposable income is what services debt.
    net_pay           DOUBLE PRECISION              NOT NULL,

    -- WEEKLY | BIWEEKLY | SEMIMONTHLY | MONTHLY
    -- Determines the multiplier used to normalise net_pay to a monthly
    -- equivalent: 4.33, 2.166, 2.0, 1.0 respectively.
    -- Declared length is the Hibernate default, not a domain constraint.
    pay_frequency     VARCHAR(255),

    pay_period_end    DATE                          NOT NULL,
    pay_period_start  DATE                          NOT NULL,

    -- Server-side ingest time, not a value supplied by the caller. Stored with
    -- time zone so the instant is unambiguous regardless of where the host runs.
    received_at       TIMESTAMP(6) WITH TIME ZONE   NOT NULL,

    -- Originating payroll provider, for data lineage attribution.
    source_provider   VARCHAR(255),

    -- Worker identifier supplied by the calling system. Pseudonymous.
    user_id           VARCHAR(255)                  NOT NULL
);


-- -----------------------------------------------------------------------------
-- income_verification_result
--
-- The current income assessment for a worker. Exactly one row per worker,
-- recomputed in full and overwritten on every incoming payroll event.
--
-- Note the difference in mutability from payroll_event_record above and from
-- eligibility_decision in the decisions database: this table holds current
-- state, not history. Consumers that need a point-in-time value must snapshot
-- it themselves rather than referencing this row later.
-- -----------------------------------------------------------------------------
CREATE TABLE income_verification_result (
    user_id                  VARCHAR(255)                  PRIMARY KEY,

    -- Mean of the monthly-equivalent net pay across the window. Not a sum,
    -- and not annualised.
    average_monthly_income   DOUBLE PRECISION              NOT NULL,

    -- clamp(1 - stddev/mean, 0, 1) over the window.
    -- Measures predictability, not magnitude.
    income_confidence_score  DOUBLE PRECISION              NOT NULL,

    -- STABLE | MODERATE | VOLATILE | INSUFFICIENT_DATA
    -- Categorical band over the score, so consumers branch on a stable enum
    -- rather than hard-coding thresholds that may be retuned.
    -- Declared length is the Hibernate default, not a domain constraint.
    income_stability_label   VARCHAR(255)                  NOT NULL,

    last_updated             TIMESTAMP(6) WITH TIME ZONE   NOT NULL,

    -- Window size actually used, capped at 12.
    pay_events_considered    INTEGER                       NOT NULL
);


-- -----------------------------------------------------------------------------
-- Indexes present in the live database
--
--   payroll_event_record_pkey        PRIMARY KEY, btree (id)
--   income_verification_result_pkey  PRIMARY KEY, btree (user_id)
--
-- Nothing else. The rolling-window query that runs on every incoming event
-- filters on user_id and orders by pay_period_start, and is therefore a
-- sequential scan. See recommended-indexes.sql.
-- -----------------------------------------------------------------------------
