-- =============================================================================
-- Database: incomeverification
-- Owner:    income-verification-service
--
-- This file documents the schema currently generated by Hibernate from the
-- JPA entity classes. It is reference documentation, not a migration: the
-- running database is created by Hibernate, not by executing this file.
--
-- Verify against the live database before relying on it:
--     ./verify-schema.sh
-- =============================================================================


-- -----------------------------------------------------------------------------
-- payroll_event_record
--
-- Historical record of every payroll event received for a worker. Retained so
-- that the confidence score can be computed over a rolling window rather than
-- from a single observation. Rows are inserted, never updated.
-- -----------------------------------------------------------------------------
CREATE TABLE payroll_event_record (
    id                BIGSERIAL         PRIMARY KEY,

    -- Worker identifier supplied by the calling system. Pseudonymous.
    user_id           VARCHAR(128)      NOT NULL,

    employer_name     VARCHAR(255),

    pay_period_start  DATE              NOT NULL,
    pay_period_end    DATE              NOT NULL,

    -- Earnings before deductions. Retained for completeness; not used in scoring.
    gross_pay         DOUBLE PRECISION  NOT NULL,

    -- Earnings after deductions. This is the value the confidence score is
    -- computed from, since disposable income is what services debt.
    net_pay           DOUBLE PRECISION  NOT NULL,

    -- WEEKLY | BIWEEKLY | SEMIMONTHLY | MONTHLY
    -- Determines the multiplier used to normalise net_pay to a monthly
    -- equivalent: 4.33, 2.166, 2.0, 1.0 respectively.
    pay_frequency     VARCHAR(32),

    -- Originating payroll provider, for data lineage attribution.
    source_provider   VARCHAR(64),

    -- Server-side ingest time, not a value supplied by the caller.
    received_at       TIMESTAMP         NOT NULL
);


-- -----------------------------------------------------------------------------
-- income_verification_result
--
-- The current income assessment for a worker. Exactly one row per worker,
-- recomputed in full and overwritten on every incoming payroll event.
--
-- Note the difference in mutability from payroll_event_record above and from
-- eligibility_decision in the decisions database: this table holds current
-- state, not history. Consumers that need a point-in-time value must snapshot
-- it themselves rather than referencing this row later.
-- -----------------------------------------------------------------------------
CREATE TABLE income_verification_result (
    user_id                  VARCHAR(128)      PRIMARY KEY,

    -- Mean of the monthly-equivalent net pay across the window. Not a sum,
    -- and not annualised.
    average_monthly_income   DOUBLE PRECISION  NOT NULL,

    -- clamp(1 - stddev/mean, 0, 1) over the window.
    -- Measures predictability, not magnitude.
    income_confidence_score  DOUBLE PRECISION  NOT NULL,

    -- STABLE | MODERATE | VOLATILE | INSUFFICIENT_DATA
    -- Categorical band over the score, so consumers branch on a stable enum
    -- rather than hard-coding thresholds that may be retuned.
    income_stability_label   VARCHAR(32)       NOT NULL,

    -- Window size actually used, capped at 12.
    pay_events_considered    INTEGER           NOT NULL,

    last_updated             TIMESTAMP         NOT NULL
);
