#!/usr/bin/env bash
#
# verify-schema.sh — Dump the live schema for comparison against the DDL in
# this directory.
#
# The relational schema is generated by Hibernate from JPA annotations, so the
# .sql files here are documentation rather than the source of truth. They drift
# silently whenever an annotation changes. Run this before citing them.
#
# Run ON THE EC2 HOST (or wherever docker compose is running) from the
# repository root:
#
#     ./docs/data-model/schema/verify-schema.sh
#
# Compare the output against incomeverification.sql and decisions.sql. If they
# differ, the .sql files are wrong — the database is authoritative.

set -euo pipefail

PSQL_USER="${PSQL_USER:-credit_platform}"

echo "==============================================================="
echo " PostgreSQL — database: incomeverification"
echo "==============================================================="
echo ""
echo "--- payroll_event_record ---"
docker compose exec -T postgres psql -U "$PSQL_USER" -d incomeverification \
  -c '\d+ payroll_event_record'

echo ""
echo "--- income_verification_result ---"
docker compose exec -T postgres psql -U "$PSQL_USER" -d incomeverification \
  -c '\d+ income_verification_result'

echo ""
echo "==============================================================="
echo " PostgreSQL — database: decisions"
echo "==============================================================="
echo ""
echo "--- eligibility_decision ---"
docker compose exec -T postgres psql -U "$PSQL_USER" -d decisions \
  -c '\d+ eligibility_decision'

echo ""
echo "==============================================================="
echo " PostgreSQL — indexes actually present"
echo "==============================================================="
echo ""
echo "Anything beyond the primary key indexes means recommended-indexes.sql"
echo "has been partially applied and this document needs updating."
echo ""
for db in incomeverification decisions; do
  echo "--- $db ---"
  docker compose exec -T postgres psql -U "$PSQL_USER" -d "$db" -c \
    "SELECT tablename, indexname, indexdef
       FROM pg_indexes
      WHERE schemaname = 'public'
      ORDER BY tablename, indexname;"
done

echo ""
echo "==============================================================="
echo " PostgreSQL — constraints actually present"
echo "==============================================================="
echo ""
for db in incomeverification decisions; do
  echo "--- $db ---"
  docker compose exec -T postgres psql -U "$PSQL_USER" -d "$db" -c \
    "SELECT conrelid::regclass AS table_name,
            conname          AS constraint_name,
            pg_get_constraintdef(oid) AS definition
       FROM pg_constraint
      WHERE connamespace = 'public'::regnamespace
      ORDER BY conrelid::regclass::text, conname;"
done

echo ""
echo "==============================================================="
echo " MongoDB — database: creditprofile"
echo "==============================================================="
echo ""
echo "--- collections ---"
docker compose exec -T mongo mongosh creditprofile --quiet --eval \
  'db.getCollectionNames().forEach(c => print("  " + c))'

echo ""
echo "--- indexes on credit_profiles ---"
docker compose exec -T mongo mongosh creditprofile --quiet --eval \
  'db.credit_profiles.getIndexes().forEach(i => print("  " + JSON.stringify(i)))'

echo ""
echo "--- validator on credit_profiles ---"
echo "  (empty output means no schema validator is configured)"
docker compose exec -T mongo mongosh creditprofile --quiet --eval \
  'const c = db.getCollectionInfos({name: "credit_profiles"});
   if (c.length && c[0].options && c[0].options.validator) {
     print(JSON.stringify(c[0].options.validator, null, 2));
   }'

echo ""
echo "--- inferred field shape from a sample document ---"
docker compose exec -T mongo mongosh creditprofile --quiet --eval \
  'const d = db.credit_profiles.findOne();
   if (!d) { print("  collection is empty"); }
   else {
     Object.keys(d).forEach(k => {
       const v = d[k];
       const t = Array.isArray(v) ? "array[" + v.length + "]"
               : v === null ? "null"
               : typeof v;
       print("  " + k.padEnd(28) + t);
     });
   }'

echo ""
echo "==============================================================="
echo " Done."
echo ""
echo " Compare against:"
echo "   docs/data-model/schema/incomeverification.sql"
echo "   docs/data-model/schema/decisions.sql"
echo "   docs/data-model/schema/creditprofile.schema.json"
echo ""
echo " Where they disagree, correct the files — not the database."
echo "==============================================================="
